services:
  service:
    container_name: service
    image: 'example/example-service:latest'
    ports:
      - "8080:8080"
  prometheus:
    container_name: prometheus
    image: 'example/prometheus:latest'
    ports:
      - "9090:9090"