services:
  service:
    container_name: service
    image: 'milleral/example-service:latest'
    ports:
      - "8080:8080"
  prometheus:
    container_name: prom
    image: 'milleral/prometheus:latest'
    ports:
      - "9090:9090"