groups:
  - name: general
    rules:
      - alert: ApplicationDown
        expr: up == 0
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: Application '{{ $labels.application }}' in environment '{{ $labels.environment }}' is down
          description: Application '{{ $labels.application }}' in environment '{{ $labels.environment }}' has been down for more then 10 seconds
      - alert: MemoryUsage
        expr: sum(jvm_memory_used_bytes{area="heap"}) by (application, environment) /
          sum(jvm_memory_max_bytes{area="heap"}) by (application, environment) * 100 > 95
        for: 5m
        labels:
          severity: critical
        annotations:
          summmary: Memory alert for application '{{ $labels.application }}' in environment '{{ $labels.instance }}'
          description: Application '{{ $labels.application }}' in environment '{{ $labels.instance }}' memory usage is
            high at {{ humanize $value}}%
      - alert: HighDiskUsage
        expr: (100 - (disk_free_bytes / disk_total_bytes) * 100) >= 85
        labels:
          severity: critical
        annotations:
          summary: 85% or greater disk is being used in application '{{ $labels.application }}'
          description: 85% or greater disk is being used in application '{{ $labels.application }}' in environment {{ $labels.environment }}'
      - alert: ExampleCounterHighCount
        expr: test_counter_total >= 5
        labels:
          severity: critical
        annotations:
          summary: High increment counter value in '{{ $labels.application }}' in environment '{{ $labels.instance }}'
          description: Application '{{ $labels.application }}' in environment '{{ $labels.instance }}' counter value is
            high at {{ humanize $value}}
      - alert: HighExampleLatency
        expr: method_timed_seconds{method="slowRequest",quantile="0.5"} > 0.01
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: Slow example request in '{{ $labels.application }}' in environment '{{ $labels.instance }}'
          description: Slow example request in '{{ $labels.application }}' in environment '{{ $labels.instance }}'. 
            The median value is {{ humanize $value}}